#!/usr/bin/env bash

 # Check for active network interface
 while true; do 
 if ip route | grep -q "default"; then
     interface=$(ip route | grep default | awk '{print $5}' | head -n1)
     if [[ $interface == wl* ]]; then
         # Wireless connection
         signal=$(sudo grep "^\s*$interface:" /proc/net/wireless | awk '{print int($3 * 70 / 70)"%"}')
         echo "N ${signal}"
     else
         # Wired connection
         echo "N󰱓Wired"
     fi
 else
     echo "N%{F$CRITICAL_COLOR}󰤮 Offline%{F-}"
 fi
 sleep 2
done
