#!/usr/bin/env bash

SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
source $SCRIPTPATH/style

while true; do
    cpu_usage=$(top -bn1 | grep "Cpu(s)" | sed "s/.*, *\([0-9.]*\)%* id.*/\1/" | awk '{print 100 - $1}')
    if (( $(echo "$cpu_usage > 80" | bc -l) )); then
      echo "CPU%{F$CRITICAL_COLOR}$CPU_USAGE_ICON ${cpu_usage}%%%{F-}"
    elif (( $(echo "$cpu_usage > 50" | bc -l) )); then 
      echo "CPU%{F$WARNING_COLOR}$CPU_USAGE_ICON ${cpu_usage}%%%{F-}"
    else 
      echo "CPU$CPU_USAGE_ICON ${cpu_usage}%"
    fi
    sleep 2
done
